import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div className='bg-light dark:bg-dark'>
      <Head>
        <title>Cristopher D. Chavez | cristodca.com</title>
        <meta 
          name="description" 
          content="Generated by create next app" 
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="main-container py-8 min-h-screen md:flex flex-col justify-center">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 w-full">
          <div className='flex flex-col justify-center items-start'>
            <h1 className='hyper-title text-dark bg-secondary rounded px-3 py-2 text-7xl mb-4'>Cristopher D. Chavez</h1>
            <h2 className='text-secondary bg-dark p-3 rounded inline-block text-5xl'>Frontend Developer</h2>
          </div>
          <div>
            <p className="normal-text">
              🧑🏻‍💻 Soy una persona de <span className="featured-tag">22 años</span> y vivo en Guadalajara, Jalisco.
            </p>
            <p className="normal-text">
              Conocí la programación hace 7 años y desde entonces no he parado de sentir curiosidad. Me encantan las <span className="featured-tag">tecnologías web</span>, sobre todo las enfocadas en <span className="featured-tag">Javascript</span>. 🥰
            </p>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  )
}

export default Home
